name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install xvfb tigervnc-standalone-server tigervnc-common

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk+fx
          cache: maven

      - name: Build (Maven)
        run: |
          echo "starting vnc server on DISPLAY:90"
          export DISPLAY=:90
          mkdir /home/runner/.vnc
          echo 123456 | vncpasswd -f > /home/runner/.vnc/passwd
          chmod -v 600 /home/runner/.vnc/passwd
          vncserver :90 -localhost -nolisten tcp
          echo "run maven build"
          mvn verify -Dintegration.skip=false
          echo "stopping vnc server"
          vncserver -kill :90
          echo "That's All, folks !"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: marlinFX-build
          path: target/marlinfx-*.jar

