name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk+fx
          cache: maven

      - name: Build (Maven)
        run: |
          mvn verify
          echo "That's All, folks !"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: marlinFX-build
          path: target/marlinfx-*.jar

